apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata: 
  name: letsencrypt
  namespace: cert-manager
spec: 
  acme: 
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "exemplo@valchan.com.br"
    privateKeySecretRef: 
      name: letsencrypt-secret
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
# kubectl apply -f cluster-issuer.yaml
# kubectl get certificates -> read precisa estar True
